/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedBrandsRouteImport } from './routes/_authenticated/brands'
import { Route as ApiPublicFalWebhookRouteImport } from './routes/api/public/fal-webhook'
import { Route as AuthenticatedStudioNewRouteImport } from './routes/_authenticated/studio.new'
import { Route as AuthenticatedStudioProjectIdRouteImport } from './routes/_authenticated/studio.$projectId'
import { Route as AuthenticatedSeriesNewRouteImport } from './routes/_authenticated/series.new'
import { Route as AuthenticatedSeriesSeriesIdRouteImport } from './routes/_authenticated/series.$seriesId'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBrandsRoute = AuthenticatedBrandsRouteImport.update({
  id: '/brands',
  path: '/brands',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicFalWebhookRoute = ApiPublicFalWebhookRouteImport.update({
  id: '/api/public/fal-webhook',
  path: '/api/public/fal-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedStudioNewRoute = AuthenticatedStudioNewRouteImport.update({
  id: '/studio/new',
  path: '/studio/new',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStudioProjectIdRoute =
  AuthenticatedStudioProjectIdRouteImport.update({
    id: '/studio/$projectId',
    path: '/studio/$projectId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSeriesNewRoute = AuthenticatedSeriesNewRouteImport.update({
  id: '/series/new',
  path: '/series/new',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSeriesSeriesIdRoute =
  AuthenticatedSeriesSeriesIdRouteImport.update({
    id: '/series/$seriesId',
    path: '/series/$seriesId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/brands': typeof AuthenticatedBrandsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/series/$seriesId': typeof AuthenticatedSeriesSeriesIdRoute
  '/series/new': typeof AuthenticatedSeriesNewRoute
  '/studio/$projectId': typeof AuthenticatedStudioProjectIdRoute
  '/studio/new': typeof AuthenticatedStudioNewRoute
  '/api/public/fal-webhook': typeof ApiPublicFalWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/brands': typeof AuthenticatedBrandsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/series/$seriesId': typeof AuthenticatedSeriesSeriesIdRoute
  '/series/new': typeof AuthenticatedSeriesNewRoute
  '/studio/$projectId': typeof AuthenticatedStudioProjectIdRoute
  '/studio/new': typeof AuthenticatedStudioNewRoute
  '/api/public/fal-webhook': typeof ApiPublicFalWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/brands': typeof AuthenticatedBrandsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/_authenticated/series/$seriesId': typeof AuthenticatedSeriesSeriesIdRoute
  '/_authenticated/series/new': typeof AuthenticatedSeriesNewRoute
  '/_authenticated/studio/$projectId': typeof AuthenticatedStudioProjectIdRoute
  '/_authenticated/studio/new': typeof AuthenticatedStudioNewRoute
  '/api/public/fal-webhook': typeof ApiPublicFalWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/sitemap.xml'
    | '/brands'
    | '/dashboard'
    | '/.lovable/oauth/consent'
    | '/series/$seriesId'
    | '/series/new'
    | '/studio/$projectId'
    | '/studio/new'
    | '/api/public/fal-webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/sitemap.xml'
    | '/brands'
    | '/dashboard'
    | '/.lovable/oauth/consent'
    | '/series/$seriesId'
    | '/series/new'
    | '/studio/$projectId'
    | '/studio/new'
    | '/api/public/fal-webhook'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/sitemap.xml'
    | '/_authenticated/brands'
    | '/_authenticated/dashboard'
    | '/.lovable/oauth/consent'
    | '/_authenticated/series/$seriesId'
    | '/_authenticated/series/new'
    | '/_authenticated/studio/$projectId'
    | '/_authenticated/studio/new'
    | '/api/public/fal-webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  ApiPublicFalWebhookRoute: typeof ApiPublicFalWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/brands': {
      id: '/_authenticated/brands'
      path: '/brands'
      fullPath: '/brands'
      preLoaderRoute: typeof AuthenticatedBrandsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/fal-webhook': {
      id: '/api/public/fal-webhook'
      path: '/api/public/fal-webhook'
      fullPath: '/api/public/fal-webhook'
      preLoaderRoute: typeof ApiPublicFalWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/studio/new': {
      id: '/_authenticated/studio/new'
      path: '/studio/new'
      fullPath: '/studio/new'
      preLoaderRoute: typeof AuthenticatedStudioNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/studio/$projectId': {
      id: '/_authenticated/studio/$projectId'
      path: '/studio/$projectId'
      fullPath: '/studio/$projectId'
      preLoaderRoute: typeof AuthenticatedStudioProjectIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/series/new': {
      id: '/_authenticated/series/new'
      path: '/series/new'
      fullPath: '/series/new'
      preLoaderRoute: typeof AuthenticatedSeriesNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/series/$seriesId': {
      id: '/_authenticated/series/$seriesId'
      path: '/series/$seriesId'
      fullPath: '/series/$seriesId'
      preLoaderRoute: typeof AuthenticatedSeriesSeriesIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedBrandsRoute: typeof AuthenticatedBrandsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedSeriesSeriesIdRoute: typeof AuthenticatedSeriesSeriesIdRoute
  AuthenticatedSeriesNewRoute: typeof AuthenticatedSeriesNewRoute
  AuthenticatedStudioProjectIdRoute: typeof AuthenticatedStudioProjectIdRoute
  AuthenticatedStudioNewRoute: typeof AuthenticatedStudioNewRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedBrandsRoute: AuthenticatedBrandsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedSeriesSeriesIdRoute: AuthenticatedSeriesSeriesIdRoute,
  AuthenticatedSeriesNewRoute: AuthenticatedSeriesNewRoute,
  AuthenticatedStudioProjectIdRoute: AuthenticatedStudioProjectIdRoute,
  AuthenticatedStudioNewRoute: AuthenticatedStudioNewRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  ApiPublicFalWebhookRoute: ApiPublicFalWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
