/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedBrandsRouteImport } from './routes/_authenticated/brands'
import { Route as ApiPublicFalWebhookRouteImport } from './routes/api/public/fal-webhook'
import { Route as AuthenticatedStudioNewRouteImport } from './routes/_authenticated/studio.new'
import { Route as AuthenticatedStudioProjectIdRouteImport } from './routes/_authenticated/studio.$projectId'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBrandsRoute = AuthenticatedBrandsRouteImport.update({
  id: '/brands',
  path: '/brands',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicFalWebhookRoute = ApiPublicFalWebhookRouteImport.update({
  id: '/api/public/fal-webhook',
  path: '/api/public/fal-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedStudioNewRoute = AuthenticatedStudioNewRouteImport.update({
  id: '/studio/new',
  path: '/studio/new',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStudioProjectIdRoute =
  AuthenticatedStudioProjectIdRouteImport.update({
    id: '/studio/$projectId',
    path: '/studio/$projectId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/brands': typeof AuthenticatedBrandsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/studio/$projectId': typeof AuthenticatedStudioProjectIdRoute
  '/studio/new': typeof AuthenticatedStudioNewRoute
  '/api/public/fal-webhook': typeof ApiPublicFalWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/brands': typeof AuthenticatedBrandsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/studio/$projectId': typeof AuthenticatedStudioProjectIdRoute
  '/studio/new': typeof AuthenticatedStudioNewRoute
  '/api/public/fal-webhook': typeof ApiPublicFalWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/brands': typeof AuthenticatedBrandsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/studio/$projectId': typeof AuthenticatedStudioProjectIdRoute
  '/_authenticated/studio/new': typeof AuthenticatedStudioNewRoute
  '/api/public/fal-webhook': typeof ApiPublicFalWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/sitemap.xml'
    | '/brands'
    | '/dashboard'
    | '/studio/$projectId'
    | '/studio/new'
    | '/api/public/fal-webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/sitemap.xml'
    | '/brands'
    | '/dashboard'
    | '/studio/$projectId'
    | '/studio/new'
    | '/api/public/fal-webhook'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/sitemap.xml'
    | '/_authenticated/brands'
    | '/_authenticated/dashboard'
    | '/_authenticated/studio/$projectId'
    | '/_authenticated/studio/new'
    | '/api/public/fal-webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiPublicFalWebhookRoute: typeof ApiPublicFalWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/brands': {
      id: '/_authenticated/brands'
      path: '/brands'
      fullPath: '/brands'
      preLoaderRoute: typeof AuthenticatedBrandsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/fal-webhook': {
      id: '/api/public/fal-webhook'
      path: '/api/public/fal-webhook'
      fullPath: '/api/public/fal-webhook'
      preLoaderRoute: typeof ApiPublicFalWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/studio/new': {
      id: '/_authenticated/studio/new'
      path: '/studio/new'
      fullPath: '/studio/new'
      preLoaderRoute: typeof AuthenticatedStudioNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/studio/$projectId': {
      id: '/_authenticated/studio/$projectId'
      path: '/studio/$projectId'
      fullPath: '/studio/$projectId'
      preLoaderRoute: typeof AuthenticatedStudioProjectIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedBrandsRoute: typeof AuthenticatedBrandsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedStudioProjectIdRoute: typeof AuthenticatedStudioProjectIdRoute
  AuthenticatedStudioNewRoute: typeof AuthenticatedStudioNewRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedBrandsRoute: AuthenticatedBrandsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedStudioProjectIdRoute: AuthenticatedStudioProjectIdRoute,
  AuthenticatedStudioNewRoute: AuthenticatedStudioNewRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiPublicFalWebhookRoute: ApiPublicFalWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
